name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: site/package-lock.json

      - name: Install dependencies
        working-directory: site
        run: npm ci

      - name: Build Astro site
        working-directory: site
        run: npm run build

      - name: Run accessibility audit
        working-directory: site
        run: npm run a11y:ci

      - name: Audit production dependencies
        working-directory: site
        run: npm audit --production
